Added flight_computer.py and FlightComputer class
UVicRocketry/Xenia1-Flight-Computer pull request #135
Opened 2022-07-14 19:47 UTC by JackCotter

Added flight_computer.py and FlightComputer class so that functions can be easily accessed in main

2022-07-21 01:45 UTC, lisaundre commented on src/main.py
> +    flight_computer.startup()
The FlightComputer init() also runs the startup function, we don't need it twice

2022-07-21 02:29 UTC, klemie requested changes
🥲

2022-07-21 02:29 UTC, klemie commented on src/flight_computer.py
> +            if time.time() > (time_at_start + 5):
Make these constants or global no magic number bb

2022-07-21 02:29 UTC, klemie commented on src/flight_computer.py
> +            elif self.rocket_data.current_altitude < -9:
same thing with this -9

2022-07-21 02:29 UTC, klemie commented on src/flight_computer.py
> +            elif self.rocket_data.current_altitude < -9:
how does the altitude be negative do we have a drill

2022-07-21 02:29 UTC, klemie commented on src/flight_computer.py
> +            if time.time > (time_at_start + 480):
magic number (480)

2022-07-21 02:29 UTC, klemie commented on src/flight_computer.py
> +            elif self.rocket_data.current_altitude < -9:
current acceleration?

2022-07-21 02:29 UTC, klemie commented on src/flight_computer.py
> +            if time.time > (time_at_start + 300):
300 is magic

2022-07-21 02:29 UTC, klemie commented on src/flight_computer.py
> +            if time.time() > (time_at_start + 5):
change to powered flight timeout

2022-07-21 20:04 UTC, JackCotter commented on src/flight_computer.py
> +        self.rocket_data = RocketData()
@macsyd made a pull request. resolving.

2022-07-22 03:20 UTC, klemie approved these changes

2022-07-22 03:20 UTC, merged