GPIOReader Mocks
UVicRocketry/Xenia1-flight-Computer pull request #44
Opened 2022-03-01 02:40 UTC by JackCotter

Test mode added to main function. Test mode can be activated by typing "True" into command line prompt

mocks added to GPIOReader to generate random input from BME and LSM sensors. This will allow easy testing of other functions.

2022-03-01 03:32 UTC, krislemie requested changes

2022-03-01 03:32 UTC, krislemie commented on src/main.py
> +from xmlrpc.client import boolean
Dont think this is nesscary. I believe Bool is built in to python so you should be able to delete this line

2022-03-01 03:32 UTC, krislemie commented on src/main.py
> +    test_mode = bool(input("Activate Test Mode (True/False):"))
Did some looking to this. bool casting makes empty strings false and non-empty string true no matter what they are. I think theres a library that converts "true" -> True (bool). Try to change it to that

2022-03-01 03:32 UTC, krislemie commented on src/gpioReader.py
> +import math
You can delete this its not needed anymore

2022-03-01 03:32 UTC, krislemie commented on src/gpioReader.py
> +    'a': float,
tab these in for formatting

2022-03-01 03:32 UTC, krislemie commented on src/gpioReader.py
> +        # lsmobject = GeneralLSMObject()
delete these comments

2022-03-01 03:36 UTC, klemie requested changes

2022-03-01 03:36 UTC, klemie commented on src/gpioReader.py
> +    'c': float
```suggestion
      'a': float,
      'b': float,
      'c': float
```

2022-03-01 07:48 UTC, klemie approved these changes
Very cool kanye

2022-03-01 07:48 UTC, krislemie approved these changes
Even cooler kanye

2022-03-02 07:29 UTC, klemie requested changes

2022-03-02 07:29 UTC, klemie commented on src/main.py
> +    if len(sys.argv)>1:
```suggestion
    if len(sys.argv) > 1:
```

2022-03-02 07:29 UTC, klemie commented on src/main.py
> +        if sys.argv[1]=="test":
```suggestion
        if sys.argv[1] == "test":
```

2022-03-02 07:29 UTC, klemie commented on src/main.py
> +            test_mode=True
```suggestion
            test_mode = True
```

2022-03-02 07:29 UTC, klemie commented on src/rocketData.py
> +    def convert_to_csv(self):
This will cause merge conflicts. I know its wrong but its been addressed in a different branch
```suggestion
    def convert_to_csv(self)
```

2022-03-02 07:29 UTC, klemie commented on src/rocketData.py
> +    def convert_antenna_format(self):
```suggestion
    def convert_antenna_format(self)
```
same as other

2022-03-08 05:41 UTC, merged