X1-AV-27
UVicRocketry/Xenia1-flight-Computer pull request #59
Opened 2022-05-04 06:49 UTC by lisaundre

updated sensor data

2022-05-11 06:07 UTC, klemie requested changes
Looks good on my first look over just some small things. Will look deeper tomorrow

2022-05-11 06:07 UTC, klemie commented on src/rocketData.py
> +            print("LSM accepts 10 values in this order: Acceleration (x, y, z), magentometer (x, y, z), gyroscope (x, y, z")
```suggestion
            print("LSM accepts 10 values in this order: Acceleration (x, y, z), magentometer (x, y, z), gyroscope (x, y, z)")
```
forgot a closing brace

2022-05-11 06:07 UTC, klemie commented on src/dataHandler.py
> +   test
test?

2022-05-12 16:41 UTC, krislemie commented on src/dataHandler.py
> +   test
Test!

2022-05-12 17:07 UTC, merged